version: '3'

services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always


  app:
    container_name: app
    build: ./app
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    restart: always
